# Backpropagation y Autogradient

1. [Pytorch Autograd Engine](https://pytorch.org/blog/overview-of-pytorch-autograd-engine/)

2. [Como se construyen los grafos computacionales en Pytorch](https://pytorch.org/blog/computational-graphs-constructed-in-pytorch/)

3. [Como se ejecutan los grafos computacionales en Pytorch](https://pytorch.org/blog/how-computational-graphs-are-executed-in-pytorch/)

## Calculo automatico del gradiente:

## y = x^2

In [ ]:
import torch 
x = torch.tensor([[2.0]], requires_grad=True)
y = x**2
y.backward()
print(x.grad)

## Un poco mas complejo (grafos de calculos):

## f = (x + y) * z 

#### lo podemos escribir: f = q * z donde q = x + y
 
![image](img/backprop.png)

#### Entradas:
```
x = -2; y = 5; z = -4
```

#### Paso hacia adelante:
```
q = x + y   --->   3 

f = q * z   --->   3 * -4 = -12 
```

#### Primer paso del backprop: f = q * z
```
df/dz = q   --->   3

df/dq = z   --->   -4
```

#### Segundo paso del backprop: q = x + y
```
df/dx = df/dq * dq/dx   --->   z * 1 = -4

df/dy = df/dq * dq/dy   --->   z * 1 = -4
```

In [14]:
x = torch.tensor([[-2.0]], requires_grad=True)
y = torch.tensor([[5.0]], requires_grad=True)
z = torch.tensor([[-4.0]], requires_grad=True)
q = x + y 
f = q * z 
f.backward()     # calculo automatico del gradiente

print(z.grad)    #df/dz = q => x + y = 3 

print(x.grad)    #df/dx = df/dq * dq/dx = z * 1 = -4
print(y.grad)    #df/dy = df/dq * dq/dy = z * 1 = -4

tensor([[3.]])
tensor([[-4.]])
tensor([[-4.]])
