In [ ]:
#https://numpy.org/learn/
#https://numpy.org/devdocs/user/absolute_beginners.html

In [15]:
import numpy as np

## Creacion de Arrays

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
np.zeros(2)

array([0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.empty(5) #con lo que haya en la memoria

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [21]:
np.arange(4) #como la funcion range

array([0, 1, 2, 3])

In [23]:
np.linspace(0, 10, num=5) #del 0 al 10 cinco numeros igualmente espaciados

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.ones(2, dtype=np.int64) #elegir el tipo de dato

array([1, 1])

## Concatenar y agregar elementos

In [24]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [25]:
#https://numpy.org/devdocs/reference/generated/numpy.concatenate.html
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [41]:
np.concatenate((a, b), axis=0) #axis=0 : eje de las filas (o sea por columnas)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
np.concatenate((a, b.T), axis=1) #axis=1 : eje de las columnas (o sea por filas)

array([[1, 2, 5],
       [3, 4, 6]])

In [43]:
np.concatenate((a, b), axis=None) #axis=None flattens : convierte en unidimensional

array([1, 2, 3, 4, 5, 6])

In [49]:
a = np.array([[1, 2], [3, 4], [5,6]])
b = np.array([[[7,8,9,10,11]]])
np.concatenate((a, b), axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
a = np.array([[1, 2], [3, 4], [5,6]])
b = np.array([[[7,8,9,10,11]]])
c = np.concatenate((a, b), axis=None)
c[0] = 99
print(a)
print(b)
print(c)

[[1 2]
 [3 4]
 [5 6]]
[[[ 7  8  9 10 11]]]
[99  2  3  4  5  6  7  8  9 10 11]


## Tamaño de los arrays

In [50]:
array_ejemplo = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [52]:
array_ejemplo.shape #elementos por dimension

(3, 2, 4)

In [51]:
array_ejemplo.ndim #numero de dimensiones

3

In [53]:
array_ejemplo.size #cantidad total de elementos

24

## Modificar la cantidad de dimensiones y elementos por dimension

In [58]:
a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [59]:
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [60]:
a.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [61]:
a.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [82]:
a = np.arange(6)
b = a.reshape(2,3)
b[0,0] = 99
print(a)
print(b)

[99  1  2  3  4  5]
[[99  1  2]
 [ 3  4  5]]


## Matriz transpuesta

In [76]:
a = np.arange(6)
print(a)
print(a.T)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [77]:
a = a.reshape(2,3)
print(a)
print(a.T)
print(a.transpose())

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


In [81]:
a = np.arange(6)
b = a.T
b[0] = 99
print(a)
print(b)

[99  1  2  3  4  5]
[99  1  2  3  4  5]


## Flatten y Ravel

In [73]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
a1 = a.flatten() #crea una copia del array
a1[0] = 99
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
a2 = a.ravel() #no crea una copia del array
a2[0] = 98
print(a)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Slicing y Copy

In [ ]:
#Igual que las listas

In [85]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [86]:
a[1:3]

array([2, 3])

In [87]:
a[:3]

array([1, 2, 3])

In [88]:
a[1:]

array([2, 3, 4, 5, 6])

In [89]:
a[-1]

6

In [90]:
b = a[1:].copy()
b[0] = 99
print(a)
print(b)

[1 2 3 4 5 6]
[99  3  4  5  6]


In [91]:
c = a[1:]
c[-1] = 99
print(a)
print(c)

[ 1  2  3  4  5 99]
[ 2  3  4  5 99]


In [93]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [94]:
a[1:3,2:]

array([[ 7,  8],
       [11, 12]])

## Apilar y dividir matrices

In [98]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [100]:
np.vstack((a1, a2)) #apilar verticalmente

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [101]:
np.hstack((a1, a2)) #apilar horizontalmente

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [109]:
a = np.arange(1, 25).reshape(2, 12)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [110]:
np.hsplit(a, 3) #dividir en tres iguales

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [116]:
np.hsplit(a, (2, 10)) #especifico en que columnas quiero dividir

[array([[ 1,  2],
        [13, 14]]),
 array([[ 3,  4,  5,  6,  7,  8,  9, 10],
        [15, 16, 17, 18, 19, 20, 21, 22]]),
 array([[11, 12],
        [23, 24]])]

## Condicionales en los indices

In [17]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
print(a[a < 5])

[1 2 3 4]


In [20]:
print(a >= 5)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [21]:
a[[[False,False,False,False],
 [ True,True,True,True],
 [ True,True,True,True]]]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [160]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
np.where(a < 5) #devuelve los indices (en este caso una tupla (fila,columna))

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

## Funciones utiles

In [140]:
a = np.array([10,9,8,7,6,5,4,3,2,1])
b = np.array([[10,9,8,7,6],[5,4,3,2,1]])
print(a)
print(b)

[10  9  8  7  6  5  4  3  2  1]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [141]:
np.min(a)

1

In [142]:
np.min(b)

1

In [143]:
np.min(b,axis=0)

array([5, 4, 3, 2, 1])

In [144]:
np.min(b,axis=1)

array([6, 1])

In [145]:
np.max(a)

10

In [146]:
np.sum(a)

55

In [147]:
np.mean(a)

5.5

In [148]:
np.std(a)

2.8722813232690143

In [154]:
np.sort(b)

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [155]:
np.sort(b, axis=0)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6]])

In [156]:
np.unique([1,1,1,2,2,2,2])

array([1, 2])

## Operaciones matematicas entre matrices

In [167]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [163]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [166]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([1, 1])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [168]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b) #[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

array([[37, 40],
       [85, 92]])

In [169]:
A=np.array([[1,2],
   [3,4],
   [5,6],
   [7,8]])

B=np.array([[10,20,30],
   [40,50,60]])

C = [[1*10+2*40, 1*20+2*50, 1*30+2*60],
     [3*10+4*40, 3*20+4*50, 3*30+4*60],
     [5*10+6*40, 5*20+6*50, 5*30+6*60],
     [7*10+8*40, 7*20+8*50, 7*30+8*60]]

In [170]:
A @ B

array([[ 90, 120, 150],
       [190, 260, 330],
       [290, 400, 510],
       [390, 540, 690]])

In [172]:
np.matmul(A,B)

array([[ 90, 120, 150],
       [190, 260, 330],
       [290, 400, 510],
       [390, 540, 690]])

In [173]:
np.dot(A,B)

array([[ 90, 120, 150],
       [190, 260, 330],
       [290, 400, 510],
       [390, 540, 690]])

## Numeros Pseudoaleatorios

In [ ]:
#https://numpy.org/doc/1.16/reference/routines.random.html

In [186]:
np.random.randint(10)

0

In [187]:
np.random.randint(10, size=(15))

array([6, 9, 5, 8, 1, 9, 8, 0, 0, 8, 6, 8, 4, 7, 5])

## Vectorizacion

In [3]:
import time 

array1 = np.random.random(size=10**5)
array2 = np.random.random(size=10**5)

start_time = time.time()
for i in range(len(array1)):
    array1[i] += array2[i]
end_time = time.time()
print("Tiempo: ", end_time - start_time)

start_time = time.time()
array1 += array2
end_time = time.time()
print("Tiempo: ", end_time - start_time)

Tiempo:  0.04415416717529297
Tiempo:  0.0004930496215820312


In [4]:
import numpy as np
from timeit import Timer
 
array = np.random.randint(1000, size=10**5)
b = 42

In [5]:
def multiplicacion_por_escalar_bucle_for():
    array2 = np.empty(10**5)
    for i in range(len(array)):
        array2[i] = array[i] * b

In [6]:
def multiplicacion_por_escalar_numpy():
    array2 = array * b

In [7]:
tiempo_bucle_for = Timer(multiplicacion_por_escalar_bucle_for).timeit(100)
tiempo_numpy = Timer(multiplicacion_por_escalar_numpy).timeit(100)
 
print(f"Tiempo: {tiempo_bucle_for} usando bucle for")
print(f"Tiempo: {tiempo_numpy} usando numpy")

Tiempo: 2.6073152919998392 usando bucle for
Tiempo: 0.0028808750212192535 usando numpy


In [11]:
def suma_con_bucle_for():
    suma=0
    for item in array:
        suma += item

In [12]:
def suma_con_sum():
    suma = sum(array)

In [13]:
def suma_con_numpy():
    suma = np.sum(array)

In [14]:
tiempo_bucle_for = Timer(suma_con_bucle_for).timeit(100)
tiempo_sum = Timer(suma_con_sum).timeit(100)
tiempo_numpy = Timer(suma_con_numpy).timeit(100)
 
print(f"Tiempo: {tiempo_bucle_for} usando bucle for")
print(f"Tiempo: {tiempo_sum} usando sum")
print(f"Tiempo: {tiempo_numpy} usando numpy")

Tiempo: 0.8400722499936819 usando bucle for
Tiempo: 0.640412499953527 usando sum
Tiempo: 0.0013409579987637699 usando numpy
