# Entrenando nuestra caja negra

Es hora de entrenar nuestra caja negra. Utilizaremos nuestra tabla de Entrenamiento para entrenarla y luego una vez que tenemos la caja entrenada la usaremos para predecir nuevos valores que nunca ha visto. Veamos el siguiente diagrama para entender como funciona el procedimiento:

![Proceso entrenamiento caja negra](img/proceso_caja_negra.png)

Cargamos nuestra tabla de entrenamiento:

In [1]:
import pandas as pd

In [2]:
df_train = pd.read_csv("tabla_telefonos_train.csv")

In [3]:
X = df_train.drop(columns=["Precio"])
y = df_train.Precio

Importamos una algortimo de Machine Learning (nuestra caja negra) desde la libreria sklearn. En este caso el que se llama Regresion Lineal:

In [4]:
from sklearn.linear_model import LinearRegression

Creamos nuestra caja negra:

In [5]:
caja_negra = LinearRegression()

Entrenamos nuestra caja negra:

In [6]:
caja_negra.fit(X, y)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


LinearRegression()

Y ahora ya podemos utilizar nuestra caja negra para hacer predicciones. Veamos que valor nos da para nuestro telefono:

In [18]:
mi_telefono = pd.DataFrame({
    'Memoria_64': [0],
    'Memoria_256': [1],
    'Memoria_512': [0],
    'Color_Gris': [1],
    'Color_Oro': [0],
    'Color_Verde': [0],
    'Desbloqueado_False': [0],
    'Desbloqueado_True':[1],
    'Estado_Bueno': [1],
    'Estado_Muy bueno': [1],
    'Estado_Reacondicionado': [1],
             })

In [19]:
mi_telefono

Memoria_64  Memoria_256  Memoria_512  Color_Gris  Color_Oro  Color_Verde  \
0           0            1            0           1          0            0   

   Desbloqueado_False  Desbloqueado_True  Estado_Bueno  Estado_Muy bueno  \
0                   0                  1             1                 1   

   Estado_Reacondicionado  
0                       1

In [8]:
caja_negra.predict(mi_telefono)

array([442.09])

## Como saber si mi caja negra esta bien entrenada?

Para ello utilizaremos nuestra tabla de prueba. En nuestra tabla de prueba tenemos datos que la caja negra nunca ha visto y que sabemos cual es la prediccion correcta, en nuestro caso el precio de cada telefono que recopilamos de internet. Entonces utilizamos la caja negra para predecir los precios de los telefonos que quedaron en la tabla de prueba y medimos que tan lejos esta la prediccion de los valores reales:

![Error de prediccion de caja negra](img/error_prediccion_caja_negra.png)

In [9]:
df_test = pd.read_csv("tabla_telefonos_test.csv")

In [10]:
X = df_test.drop(columns=["Precio"])

In [11]:
y_predecido = caja_negra.predict(X)
y_predecido

array([450.74, 450.74])

In [12]:
y_verdadero = df_test.Precio.to_numpy()
y_verdadero

array([499.  , 376.84])

Si restamos uno a uno los valores reales podemos ver la diferencia entre cada uno:

In [13]:
y_verdadero - y_predecido

array([ 48.26, -73.9 ])

Para obtener una medicion de cuanto ha fallado ya hay metricas estudiadas que tambien podremos utilizar desde la libreria sklearn. Esto lo veremos en la siguiente unidad.

# Fin: [Volver al contenido del curso](https://www.freecodingtour.com/cursos/espanol/datascience/datascience.html)