# Jugando con Numpy (contenido opcional)

Numpy es una libreria que tiene una cantidad enorme de funciones. Aqui solo veremos algunas de las mas utilizadas. Como decimos siempre no hace falta memorizarlas, cada vez que necesitemos hacer algo especifico podemos buscar en internet que funcion y como debemos utilizarla.

Los siguientes ejemplos estan basados en la documentacion oficial de [Numpy](https://numpy.org/devdocs/user/absolute_beginners.html)

In [ ]:
import numpy as np

## Creacion de Arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(type(a))
print(a)

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

In [ ]:
np.zeros(2)

In [ ]:
np.zeros((2,3))

In [ ]:
np.ones(2)

In [ ]:
np.empty(5) #con lo que haya en la memoria

In [ ]:
np.arange(4) #como la funcion range

In [ ]:
np.linspace(0, 10, num=5) #del 0 al 10 cinco numeros igualmente espaciados

In [ ]:
np.ones(2, dtype=np.int64) #elegir el tipo de dato

## Concatenar y agregar elementos

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
#https://numpy.org/devdocs/reference/generated/numpy.concatenate.html
np.concatenate((a, b))

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [ ]:
np.concatenate((a, b), axis=0) #axis=0 : eje de las filas (o sea por columnas)

In [ ]:
np.concatenate((a, b.T), axis=1) #axis=1 : eje de las columnas (o sea por filas)

In [ ]:
np.concatenate((a, b), axis=None) #axis=None flattens : convierte en unidimensional

In [ ]:
a = np.array([[1, 2], [3, 4], [5,6]])
b = np.array([[[7,8,9,10,11]]])
np.concatenate((a, b), axis=None)

In [ ]:
a = np.array([[1, 2], [3, 4], [5,6]])
b = np.array([[[7,8,9,10,11]]])
c = np.concatenate((a, b), axis=None)
c[0] = 99
print(a)
print(b)
print(c)

## Tamaño de los arrays

In [ ]:
array_ejemplo = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [ ]:
array_ejemplo.shape #elementos por dimension

In [ ]:
array_ejemplo.ndim #numero de dimensiones

In [ ]:
array_ejemplo.size #cantidad total de elementos

## Modificar la cantidad de dimensiones y elementos por dimension

In [ ]:
a = np.arange(8)
print(a)

In [ ]:
a.reshape(2,4)

In [ ]:
a.reshape(4,2)

In [ ]:
a.reshape(2,2,2)

In [ ]:
a = np.arange(6)
b = a.reshape(2,3)
b[0,0] = 99
print(a)
print(b)

## Matriz transpuesta

In [ ]:
a = np.arange(6)
print(a)
print(a.T)

In [ ]:
a = a.reshape(2,3)
print(a)
print(a.T)
print(a.transpose())

In [ ]:
a = np.arange(6)
b = a.T
b[0] = 99
print(a)
print(b)

## Flatten y Ravel

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

In [ ]:
a1 = a.flatten() #crea una copia del array
a1[0] = 99
print(a)

In [ ]:
a2 = a.ravel() #no crea una copia del array
a2[0] = 98
print(a)

## Slicing y Copy

In [ ]:
#Igual que las listas

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)

In [ ]:
a[1:3]

In [ ]:
a[:3]

In [ ]:
a[1:]

In [ ]:
a[-1]

In [ ]:
b = a[1:].copy()
b[0] = 99
print(a)
print(b)

In [ ]:
c = a[1:]
c[-1] = 99
print(a)
print(c)

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

In [ ]:
a[1:3,2:]

## Apilar y dividir matrices

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
np.vstack((a1, a2)) #apilar verticalmente

In [ ]:
np.hstack((a1, a2)) #apilar horizontalmente

In [ ]:
a = np.arange(1, 25).reshape(2, 12)
print(a)

In [ ]:
np.hsplit(a, 3) #dividir en tres iguales

In [ ]:
np.hsplit(a, (2, 10)) #especifico en que columnas quiero dividir

## Condicionales en los indices

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

In [ ]:
print(a[a < 5])

In [ ]:
print(a >= 5)

In [ ]:
a[[[False,False,False,False],
 [ True,True,True,True],
 [ True,True,True,True]]]

In [ ]:
a[(a > 2) & (a < 11)]

In [ ]:
np.where(a < 5) #devuelve los indices (en este caso una tupla (fila,columna))

## Funciones utiles

In [ ]:
a = np.array([10,9,8,7,6,5,4,3,2,1])
b = np.array([[10,9,8,7,6],[5,4,3,2,1]])
print(a)
print(b)

In [ ]:
np.min(a)

In [ ]:
np.min(b)

In [ ]:
np.min(b,axis=0)

In [ ]:
np.min(b,axis=1)

In [ ]:
np.max(a)

In [ ]:
np.sum(a)

In [ ]:
np.mean(a)

In [ ]:
np.std(a)

In [ ]:
np.sort(b)

In [ ]:
np.sort(b, axis=0)

In [ ]:
np.unique([1,1,1,2,2,2,2])

## Operaciones matematicas entre matrices

In [ ]:
data = np.array([1.0, 2.0])
data * 1.6

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([1, 1])
data + ones_row

In [ ]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b) #[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

In [ ]:
A=np.array([[1,2],
   [3,4],
   [5,6],
   [7,8]])

B=np.array([[10,20,30],
   [40,50,60]])

C = [[1*10+2*40, 1*20+2*50, 1*30+2*60],
     [3*10+4*40, 3*20+4*50, 3*30+4*60],
     [5*10+6*40, 5*20+6*50, 5*30+6*60],
     [7*10+8*40, 7*20+8*50, 7*30+8*60]]

In [ ]:
A @ B

In [ ]:
np.matmul(A,B)

In [ ]:
np.dot(A,B)

## Numeros Pseudoaleatorios

In [ ]:
#https://numpy.org/doc/1.16/reference/routines.random.html

In [ ]:
np.random.randint(10)

In [ ]:
np.random.randint(10, size=(15))

## Vectorizacion

In [ ]:
import time 

array1 = np.random.random(size=10**5)
array2 = np.random.random(size=10**5)

start_time = time.time()
for i in range(len(array1)):
    array1[i] += array2[i]
end_time = time.time()
print("Tiempo: ", end_time - start_time)

start_time = time.time()
array1 += array2
end_time = time.time()
print("Tiempo: ", end_time - start_time)

In [ ]:
import numpy as np
from timeit import Timer
 
array = np.random.randint(1000, size=10**5)
b = 42

In [ ]:
def multiplicacion_por_escalar_bucle_for():
    array2 = np.empty(10**5)
    for i in range(len(array)):
        array2[i] = array[i] * b

In [ ]:
def multiplicacion_por_escalar_numpy():
    array2 = array * b

In [ ]:
tiempo_bucle_for = Timer(multiplicacion_por_escalar_bucle_for).timeit(100)
tiempo_numpy = Timer(multiplicacion_por_escalar_numpy).timeit(100)
 
print(f"Tiempo: {tiempo_bucle_for} usando bucle for")
print(f"Tiempo: {tiempo_numpy} usando numpy")

In [ ]:
def suma_con_bucle_for():
    suma=0
    for item in array:
        suma += item

In [ ]:
def suma_con_sum():
    suma = sum(array)

In [ ]:
def suma_con_numpy():
    suma = np.sum(array)

In [ ]:
tiempo_bucle_for = Timer(suma_con_bucle_for).timeit(100)
tiempo_sum = Timer(suma_con_sum).timeit(100)
tiempo_numpy = Timer(suma_con_numpy).timeit(100)
 
print(f"Tiempo: {tiempo_bucle_for} usando bucle for")
print(f"Tiempo: {tiempo_sum} usando sum")
print(f"Tiempo: {tiempo_numpy} usando numpy")

# Algebra Lineal con Numpy

Numpy tambien tiene [funciones de algebra lineal](https://numpy.org/doc/stable/reference/routines.linalg.html)

## Angulo entre dos vectores

In [ ]:
def unit_vector(vector):
    return vector / np.linalg.norm(vector)

def angle_between(v1, v2):
    v1_u = unit_vector(v1)
    v2_u = unit_vector(v2)
    return np.arccos(np.dot(v1_u, v2_u))

def angle_degrees_between(v1, v2):
    rad = angle_between(v1, v2)
    return rad * (180/np.pi)

In [ ]:
angle_between([1,0],[0,1])*2

## Determinante

In [ ]:
m = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
m

In [ ]:
print(np.linalg.det(m))
print(6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))

## Eigenvalores y Eigenvectores

In [ ]:
m = np.diag((1, 2, 3))
m

In [ ]:
w, v = LA.eig(m)
print(w)
print(v)

# Ejercicios

### Ejercicio 1:

Crear array de numpy con 5 ceros y guardarlo en una variable de nombre a

In [ ]:
# Escribir aqui la solucion



In [ ]:
#No modificar este codigo y verificar que coincide con el resultado esperado
print(type(a))
print(type(a[0]))
print(a)

*Resultado esperado:*
```
<class 'numpy.ndarray'>
<class 'numpy.float64'>
[0. 0. 0. 0. 0.]
```

In [ ]:
#@title Solucion Ejercicio 1 {display-mode:"form"}

a = np.zeros(5)

### Ejercicio 2:

Crear array de numpy de enteros con 5 unos y guardarlo en una variable de nombre a

In [ ]:
# Escribir aqui la solucion



In [ ]:
#No modificar este codigo y verificar que coincide con el resultado esperado
print(type(a))
print(type(a[0]))
print(a)

*Resultado esperado:*
```
<class 'numpy.ndarray'>
<class 'numpy.int32'>
[1 1 1 1 1]
```

In [ ]:
#@title Solucion Ejercicio 2 {display-mode:"form"}

a = np.ones(5, dtype=np.int32)

### Ejercicio 3:

Crear array de numpy de dos dimensiones (5x5) con los numeros del 0 al 24 y guardarlo en una variable de nombre a

In [ ]:
# Escribir aqui la solucion



In [ ]:
#No modificar este codigo y verificar que coincide con el resultado esperado
print(a)

*Resultado esperado:*
```
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
```

In [ ]:
#@title Solucion Ejercicio 3 {display-mode:"form"}

a = np.arange(25).reshape(5,5)

### Ejercicio 4:

Crear array de numpy de una dimension con 5 valores entre 18 y 1 igualmente espaciados y guardarlo en una variable de nombre a

In [ ]:
# Escribir aqui la solucion



In [ ]:
#No modificar este codigo y verificar que coincide con el resultado esperado
print(a)

*Resultado esperado:*
```
[18.   13.75  9.5   5.25  1.  ]
```

In [ ]:
#@title Solucion Ejercicio 4 {display-mode:"form"}

a = np.linspace(18,1,num=5)

### Ejercicio 5:

Crear array de numpy de dos dimensiones (5x5) con todos unos y un cero en el centro y guardarlo en una variable de nombre a

In [ ]:
# Escribir aqui la solucion



In [ ]:
#No modificar este codigo y verificar que coincide con el resultado esperado
print(a)

*Resultado esperado:*
```
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
```

In [ ]:
#@title Solucion Ejercicio 5 {display-mode:"form"}

a = np.ones((5,5))
a[2,2] = 0

### Ejercicio 6:

Crear array de numpy de dos dimensiones (10x10) con ceros en los bordes y unos en el centro y guardarlo en una variable de nombre a

In [ ]:
# Escribir aqui la solucion



In [ ]:
print(a)

*Resultado esperado:*
```
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
```

In [ ]:
#@title Solucion Ejercicio 6 {display-mode:"form"}

# Solucion 1
a = np.zeros((10,10))
a[1:-1,1:-1] = 1

# Solucion 2
a = np.ones((10,10))
a[[0,-1],:] = 0
a[:,[0,-1]] = 0

### Ejercicio 7:

Usar la funcion np.concatenate() para concatenar los siguientes dos arrays:
```python
a = np.array([[1, 1], [2, 2]])
b = np.array([[3, 3]])
```
y que el resultado sea el siguiente:
```
array([[1, 2, 3],
       [1, 2, 3]])
```

In [ ]:
# Escribir aqui la solucion



<details>
<summary>Click aqui para obtener ayuda</summary>
Utilizar las transpuestas de las matrices
</details>

In [ ]:
#@title Solucion Ejercicio 7 {display-mode:"form"}

a = np.array([[1, 1], [2, 2]])
b = np.array([[3, 3]])
np.concatenate((a.T, b.T), axis=1)

### Ejercicio 8.1:

Usar condicionales en los indices crear un nuevo array c con los valores menores a 6 de la siguiente matriz:
```python
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
```

In [ ]:
# Escribir aqui la solucion



In [ ]:
print(c)

*Resultado esperado:*
```
[1 2 3 4 5]
```

In [ ]:
#@title Solucion Ejercicio 8.1 {display-mode:"form"}

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c = a[a<6]

### Ejercicio 8.2:

Usar condicionales en los indices para sumarle 100 a los valores menores a 6 de la siguiente matriz:
```python
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
```

In [ ]:
# Escribir aqui la solucion



In [ ]:
print(a)

*Resultado esperado:*
```
[[101 102 103 104]
 [105   6   7   8]
 [  9  10  11  12]]
```

In [ ]:
#@title Solucion Ejercicio 8.2 {display-mode:"form"}

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a<6] = a[a<6] + 100

### Ejercicio 8.3:

Usar condicionales en los indices para multiplicar por 2 los valores pares y menores a 10 de la siguiente matriz:
```python
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
```

In [ ]:
# Escribir aqui la solucion



In [ ]:
print(a)

*Resultado esperado:*
```
[[ 1  4  3  8]
 [ 5 12  7 16]
 [ 9 10 11 12]]
```

In [ ]:
#@title Solucion Ejercicio 8.3 {display-mode:"form"}

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[(a%2==0) & (a<10)] = a[(a%2==0) & (a<10)] * 2

### Ejercicio 8.4:

Usar condicionales en los indices para hacer cero los valores que son numeros primos de la siguiente matriz:
```python
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
```

In [ ]:
# Escribir aqui la solucion



In [ ]:
print(a)

*Resultado esperado:*
```
[[ 1  0  0  4]
 [ 0  6  0  8]
 [ 9 10  0 12]]
```

In [ ]:
#@title Solucion Ejercicio 8.4 {display-mode:"form"}

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
def isprime(x):
    return x in [2,3,5,7,11]

#isprime_vectorized = np.vectorize(lambda x: x in [2,3,5,7,11])
isprime_vectorized = np.vectorize(isprime)
prime_indexes = isprime_vectorized(a)
a[prime_indexes] = 0

### Ejercicio 9.1:

Dada la siguiente operacion vectorial:

$$ a = \begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
\end{bmatrix} $$

$$ b = \begin{bmatrix}
0 \\
1 \\
2 \\
3 \\
4 \\
\end{bmatrix} $$

$$ c_{ij} = a_{ij} + b_j $$

Vectorizar el siguiente bucle for que la implementa:
```python
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=np.int32)
b = np.array([0,1,2,4], dtype=np.int32)
c = np.empty((3,4), dtype=np.int32)
for i in range(len(a)):
    for j in range(len(a[0])):
        c[i][j] = a[i][j] + b[j]
```




y que el resultado sea el siguiente:
```
[[ 1  3  5  8]
 [ 5  7  9 12]
 [ 9 11 13 16]]
```

In [ ]:
# Escribir aqui la solucion



In [ ]:
print(c)

In [ ]:
#@title Solucion Ejercicio 9.1 {display-mode:"form"}

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=np.int32)
b = np.array([0,1,2,4], dtype=np.int32)
c = np.empty((3,4), dtype=np.int32)
c = a + b

### Ejercicio 9.2:

Dada la siguiente operacion vectorial:

$$ a = \begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
\end{bmatrix} $$

$$ b = \begin{bmatrix}
0 \\
1 \\
2 \\
\end{bmatrix} $$

$$ c_{ij} = a_{ij} + b_i $$



Vectorizar el siguiente bucle for que la implementa:
```python
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=np.int32)
b = np.array([0,1,2], dtype=np.int32)
c = np.empty((3,4), dtype=np.int32)
for i in range(len(a)):
    for j in range(len(a[0])):
        c[i][j] = a[i][j] + b[i]
```
y que el resultado sea el siguiente:
```
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]
```

In [ ]:
# Escribir aqui la solucion



In [ ]:
print(c)

In [ ]:
#@title Solucion Ejercicio 9.2 {display-mode:"form"}

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=np.int32)
b = np.array([0,1,2], dtype=np.int32)
c = np.empty((3,4), dtype=np.int32)
c = a + np.array(([b] * 4)).T

# Fin: [Volver al contenido del curso](https://www.freecodingtour.com/cursos/espanol/datascience/datascience.html)